---
pidfile: 'deploy-agent.pid'
workDir: '/tmp/deploy-agent'
logfile: '/var/log/deploy-agent.log'
trigger:
  http:
    port: 8040
stepTimeout: 60
logLevel: WARN # TRACE, DEBUG, WARN, ERROR 
tasks:
  checkInterval: 300
  concurrency: 2
preprocesses:
  maxTime: 420000
downloads:
  maxTime: 420000
autoupgrade:
  interval: 1200000
  site: https://s3.cn-north-1.amazonaws.com.cn/wanliu/deploy-agent/
