---
pidfile: 'deploy-agent.pid'
workDir: '/tmp/deploy-agent'
trigger:
  http:
    port: 8040
stepTimeout: 20
logLevel: WARN # TRACE, DEBUG, WARN, ERROR 
tasks:
  checkInterval: 300
  concurrency: 2
preprocesses:
  maxTime: 420000
downloads:
  maxTime: 420000
