#!/bin/bash

# Init file for deploy-agent
#
# chkconfig: 2345 98 02
# description: deploy-agent processes the deployments created by deploy and installs \
# the deployment artifacts on to this instance.

### BEGIN INIT INFO
# Provides:          deploy-agent
# Required-Start:    $all
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Deploy Host Agent
# Description:       deploy-agent processes the deployments created by deploy and installs
#                    the deployment artifacts on to this instance.
### END INIT INFO

export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

COMMAND=$1
RETVAL=0
[ -f /etc/profile ] && [ "`stat --format '%U %G' /etc/profile`" == "root root" ] && source /etc/profile

prog="deploy-agent"
# Modify the following USER variable to run the deploy process as a non-root user
# Note: You also need to chown /opt/deploy /var/log/ 
USER=""

AGENT_ROOT="/usr/local/lib/node_modules/deploy-agent/"
INSTALLER="/opt/deploy-agent/bin/install"
BIN="/usr/local/bin/deploy-agent"

start() {
        echo -n $"Starting $prog:"
        cd $AGENT_ROOT
        if [ $USER ]; then
          nohup sudo -i -u $USER $BIN start >/dev/null </dev/null 2>&1 # Try to start the server
        else
          nohup $BIN start >/dev/null </dev/null 2>&1  # Try to start the server
        fi
        exit $?
}

stop() {
        echo -n $"Stopping $prog:"
        cd $AGENT_ROOT
        if [ $USER ]; then
          nohup sudo -i -u $USER $BIN stop >/dev/null </dev/null 2>&1  # Try to stop the server
        else
          nohup $BIN stop >/dev/null </dev/null 2>&1  # Try to stop the server
        fi
        exit $?
}

restart() {
        echo -n $"Restarting $prog:"
        cd $AGENT_ROOT
        if [ $USER ]; then
          nohup sudo -i -u $USER $BIN restart >/dev/null </dev/null 2>&1  # Try to restart the server
        else
          nohup $BIN restart >/dev/null </dev/null 2>&1  # Try to restart the server
        fi
        exit $?
}

status() {
        cd $AGENT_ROOT
        if [ $USER ]; then
          sudo -i -u $USER $BIN status # Status of the server
        else
          $BIN status # Status of the server
        fi
        exit $?
}

update() {
        echo -n $"Updating $prog:"
        cd $AGENT_ROOT
        $INSTALLER auto #Update the agent
}

case "$COMMAND" in
        start)
                start
                ;;
        start-no-update)
                start
                ;;
        start-with-update)
                update
                start
                ;;
        stop)
                stop
                ;;
        restart)
                restart
                ;;
        force-reload)
                stop
                start
                ;;
        status)
                status
                ;;
        *)
                echo $"Usage: $0 {start|stop|status|restart}"
esac
